name: Terraform CI - S3 (No Apply)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Clona el repositorio
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      # 2Ô∏è‚É£ Instala Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      

      # 3Ô∏è‚É£ Inicializa Terraform
      - name: Terraform Init
        run: terraform init

      # 4Ô∏è‚É£ Verifica formato
      - name: Terraform Format
        run: terraform fmt -check

      # 5Ô∏è‚É£ Valida configuraci√≥n
      - name: Terraform Validate
        run: terraform validate

      # 6Ô∏è‚É£ üî• AQU√ç va el plan
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
